package csense.idea.kotlin.checked.exceptions.builtin.map.common.random

import csense.idea.kotlin.checked.exceptions.builtin.*

val ThrowingCommonRandom: Map<FqNameReceiver, BuiltInThrowingFunction> = mapOf(
//on intRange parameter...
//    FqNameReceiver(
//        fqName = "kotlin.random.nextInt",
//        receiverFqName = "kotlin.random.Random"
//    ) to BuiltInThrowingFunction(
//        "kotlin.IllegalArgumentException"
//    ),
//
// on LongRange parameter...
//    FqNameReceiver(
//        fqName = "kotlin.random.nextLong",
//        receiverFqName = "kotlin.random.Random"
//    ) to BuiltInThrowingFunction(
//        "kotlin.IllegalArgumentException"
//    ),
//The same issue for remaining Random function(s)
//The same issue for remaining URandom function(s)
)